// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task2.Repository;

#nullable disable

namespace task2.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20231004143134_UserAdd")]
    partial class UserAdd
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("task2.Core.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HP1",
                            CreatedDate = new DateTime(2023, 10, 4, 17, 31, 34, 439, DateTimeKind.Local).AddTicks(3456),
                            Name = "HP",
                            Picture = "/Images/laptop.jpg",
                            Price = 590m
                        },
                        new
                        {
                            Id = 2,
                            Code = "LEN1",
                            CreatedDate = new DateTime(2023, 10, 4, 17, 31, 34, 439, DateTimeKind.Local).AddTicks(3470),
                            Name = "Lenovo",
                            Picture = "/Images/laptop.jpg",
                            Price = 640m
                        },
                        new
                        {
                            Id = 3,
                            Code = "ASUS1",
                            CreatedDate = new DateTime(2023, 10, 4, 17, 31, 34, 439, DateTimeKind.Local).AddTicks(3472),
                            Name = "Asus",
                            Picture = "/Images/laptop.jpg",
                            Price = 750m
                        });
                });

            modelBuilder.Entity("task2.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "cenk@cenk.com",
                            Password = "12345"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
